wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.25
    cli_version: 0.25.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1773085379
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      2:
      - 1
      - 5
      - 50
      - 53
      3:
      - 4
      - 15
      - 42
      4: 3.9.25
      5: 0.25.0
      10:
      - 20
      13: linux-x86_64
    e:
      up0u8ec80qlk0nv0k23cymmezjgodq5w:
        os: Linux-6.8.0-101-generic-x86_64-with-glibc2.39
        python: CPython 3.9.25
        started_at: '2026-03-09T19:42:59.690168Z'
        args:
        - model=lrbgt
        - dataset=ABIDE
        program: -m alter.__main__
        git:
          remote_url: git@github.com:fmrifrey/ALTER.git
          commit: ad5c5a95d54aa2a0a2a275c008a692d73af293f7
        root: /home/djfrey/code/coursework/ALTER
        host: phobos
        executable: /home/djfrey/code/coursework/ALTER/alter_env/bin/python
        cpu_count: 32
        cpu_count_logical: 64
        gpu_type: NVIDIA RTX A6000
        gpu_count: 1
        disk:
          /:
            total: '3827904856064'
            used: '461548871680'
        memory:
          total: '806350245888'
        gpu_nvidia:
        - name: NVIDIA RTX A6000
          memory_total: '51527024640'
          cuda_cores: 10752
          architecture: Ampere
          uuid: GPU-2edf8929-9f4a-01aa-c972-1af528a85cc0
        cuda_version: '13.0'
        writer_id: up0u8ec80qlk0nv0k23cymmezjgodq5w
